package carsalesmanager.model;
// Generated Nov 26, 2017 6:00:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Accessory generated by hbm2java
 */
@Entity
@Table(name="accessory"
    ,catalog="carSalesManager"
)
public class Accessory  implements java.io.Serializable {


     private Integer idAccessory;
     private String name;
     private Set<Car> cars = new HashSet<Car>(0);

    public Accessory() {
    }

    public Accessory(String name, Set<Car> cars) {
       this.name = name;
       this.cars = cars;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_accessory", unique=true, nullable=false)
    public Integer getIdAccessory() {
        return this.idAccessory;
    }
    
    public void setIdAccessory(Integer idAccessory) {
        this.idAccessory = idAccessory;
    }

    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="accessories")
    public Set<Car> getCars() {
        return this.cars;
    }
    
    public void setCars(Set<Car> cars) {
        this.cars = cars;
    }




}


