package carsalesmanager.model;
// Generated Nov 26, 2017 6:00:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name="address"
    ,catalog="carSalesManager"
)
public class Address  implements java.io.Serializable {


     private Integer idAddress;
     private City city;
     private String street;
     private Integer houseNumber;
     private String complement;
     private Set<Owner> owners = new HashSet<Owner>(0);

    public Address() {
    }

    public Address(City city, String street, Integer houseNumber, String complement, Set<Owner> owners) {
       this.city = city;
       this.street = street;
       this.houseNumber = houseNumber;
       this.complement = complement;
       this.owners = owners;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_address", unique=true, nullable=false)
    public Integer getIdAddress() {
        return this.idAddress;
    }
    
    public void setIdAddress(Integer idAddress) {
        this.idAddress = idAddress;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_city")
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }

    
    @Column(name="street", length=50)
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }

    
    @Column(name="house_number")
    public Integer getHouseNumber() {
        return this.houseNumber;
    }
    
    public void setHouseNumber(Integer houseNumber) {
        this.houseNumber = houseNumber;
    }

    
    @Column(name="complement", length=15)
    public String getComplement() {
        return this.complement;
    }
    
    public void setComplement(String complement) {
        this.complement = complement;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="address")
    public Set<Owner> getOwners() {
        return this.owners;
    }
    
    public void setOwners(Set<Owner> owners) {
        this.owners = owners;
    }




}


