package carsalesmanager.model;
// Generated Nov 26, 2017 6:00:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Color generated by hbm2java
 */
@Entity
@Table(name="color"
    ,catalog="carSalesManager"
)
public class Color  implements java.io.Serializable {


     private Integer idColor;
     private String name;
     private Set<Car> cars = new HashSet<Car>(0);

    public Color() {
    }

    public Color(String name, Set<Car> cars) {
       this.name = name;
       this.cars = cars;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_color", unique=true, nullable=false)
    public Integer getIdColor() {
        return this.idColor;
    }
    
    public void setIdColor(Integer idColor) {
        this.idColor = idColor;
    }

    
    @Column(name="name", length=15)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="color")
    public Set<Car> getCars() {
        return this.cars;
    }
    
    public void setCars(Set<Car> cars) {
        this.cars = cars;
    }




}


