package carsalesmanager.model;
// Generated Nov 26, 2017 6:00:21 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name="contact"
    ,catalog="carSalesManager"
)
public class Contact  implements java.io.Serializable {


     private Integer idContact;
     private Owner owner;
     private String telephone;
     private String cell;
     private String email;

    public Contact() {
    }

    public Contact(Owner owner, String telephone, String cell, String email) {
       this.owner = owner;
       this.telephone = telephone;
       this.cell = cell;
       this.email = email;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_contact", unique=true, nullable=false)
    public Integer getIdContact() {
        return this.idContact;
    }
    
    public void setIdContact(Integer idContact) {
        this.idContact = idContact;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_owner")
    public Owner getOwner() {
        return this.owner;
    }
    
    public void setOwner(Owner owner) {
        this.owner = owner;
    }

    
    @Column(name="telephone", length=14)
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    
    @Column(name="cell", length=15)
    public String getCell() {
        return this.cell;
    }
    
    public void setCell(String cell) {
        this.cell = cell;
    }

    
    @Column(name="email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


