package carsalesmanager.model;
// Generated Nov 26, 2017 6:00:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Manufacturer generated by hbm2java
 */
@Entity
@Table(name="manufacturer"
    ,catalog="carSalesManager"
)
public class Manufacturer  implements java.io.Serializable {


     private Integer idManufacturer;
     private String name;
     private Set<Model> models = new HashSet<Model>(0);

    public Manufacturer() {
    }

    public Manufacturer(String name, Set<Model> models) {
       this.name = name;
       this.models = models;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_manufacturer", unique=true, nullable=false)
    public Integer getIdManufacturer() {
        return this.idManufacturer;
    }
    
    public void setIdManufacturer(Integer idManufacturer) {
        this.idManufacturer = idManufacturer;
    }

    
    @Column(name="name", length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="manufacturer")
    public Set<Model> getModels() {
        return this.models;
    }
    
    public void setModels(Set<Model> models) {
        this.models = models;
    }




}


