package carsalesmanager.model;
// Generated Nov 26, 2017 6:00:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Model generated by hbm2java
 */
@Entity
@Table(name="model"
    ,catalog="carSalesManager"
)
public class Model  implements java.io.Serializable {


     private Integer idModel;
     private Manufacturer manufacturer;
     private String name;
     private Set<Car> cars = new HashSet<Car>(0);

    public Model() {
    }

    public Model(Manufacturer manufacturer, String name, Set<Car> cars) {
       this.manufacturer = manufacturer;
       this.name = name;
       this.cars = cars;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_model", unique=true, nullable=false)
    public Integer getIdModel() {
        return this.idModel;
    }
    
    public void setIdModel(Integer idModel) {
        this.idModel = idModel;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_manufacturer")
    public Manufacturer getManufacturer() {
        return this.manufacturer;
    }
    
    public void setManufacturer(Manufacturer manufacturer) {
        this.manufacturer = manufacturer;
    }

    
    @Column(name="name", length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="model")
    public Set<Car> getCars() {
        return this.cars;
    }
    
    public void setCars(Set<Car> cars) {
        this.cars = cars;
    }




}


