package carsalesmanager.model;
// Generated Nov 26, 2017 6:00:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Owner generated by hbm2java
 */
@Entity
@Table(name="owner"
    ,catalog="carSalesManager"
)
public class Owner  implements java.io.Serializable {


     private Integer idOwner;
     private Address address;
     private String cpf;
     private String name;
     private Set<Sale> sales = new HashSet<Sale>(0);
     private Set<Contact> contacts = new HashSet<Contact>(0);

    public Owner() {
    }
    
     public Owner(Address address, String cpf, String name, Set<Contact> contacts) {
       this.address = address;
       this.cpf = cpf;
       this.name = name;
       this.contacts = contacts;
    }

    public Owner(Address address, String cpf, String name, Set<Sale> sales, Set<Contact> contacts) {
       this.address = address;
       this.cpf = cpf;
       this.name = name;
       this.sales = sales;
       this.contacts = contacts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_owner", unique=true, nullable=false)
    public Integer getIdOwner() {
        return this.idOwner;
    }
    
    public void setIdOwner(Integer idOwner) {
        this.idOwner = idOwner;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_address")
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }

    
    @Column(name="cpf", length=14)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="owner")
    public Set<Sale> getSales() {
        return this.sales;
    }
    
    public void setSales(Set<Sale> sales) {
        this.sales = sales;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="owner")
    public Set<Contact> getContacts() {
        return this.contacts;
    }
    
    public void setContacts(Set<Contact> contacts) {
        this.contacts = contacts;
    }




}


