package carsalesmanager.model;
// Generated Nov 26, 2017 6:00:21 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sale generated by hbm2java
 */
@Entity
@Table(name="sale"
    ,catalog="carSalesManager"
)
public class Sale  implements java.io.Serializable {


     private Integer idSale;
     private Owner owner;
     private Date saleDate;
     private Integer portionNumber;
     private Double amount;
     private Boolean settled;
     private Set<Car> cars = new HashSet<Car>(0);
     private Set<Payment> payments = new HashSet<Payment>(0);

    public Sale() {
    }

    public Sale(Owner owner, Date saleDate, Integer portionNumber, Double amount, Boolean settled, Set<Car> cars, Set<Payment> payments) {
       this.owner = owner;
       this.saleDate = saleDate;
       this.portionNumber = portionNumber;
       this.amount = amount;
       this.settled = settled;
       this.cars = cars;
       this.payments = payments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_sale", unique=true, nullable=false)
    public Integer getIdSale() {
        return this.idSale;
    }
    
    public void setIdSale(Integer idSale) {
        this.idSale = idSale;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_owner")
    public Owner getOwner() {
        return this.owner;
    }
    
    public void setOwner(Owner owner) {
        this.owner = owner;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="sale_date", length=10)
    public Date getSaleDate() {
        return this.saleDate;
    }
    
    public void setSaleDate(Date saleDate) {
        this.saleDate = saleDate;
    }

    
    @Column(name="portion_number")
    public Integer getPortionNumber() {
        return this.portionNumber;
    }
    
    public void setPortionNumber(Integer portionNumber) {
        this.portionNumber = portionNumber;
    }

    
    @Column(name="amount", precision=22, scale=0)
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    
    @Column(name="settled")
    public Boolean getSettled() {
        return this.settled;
    }
    
    public void setSettled(Boolean settled) {
        this.settled = settled;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sale")
    public Set<Car> getCars() {
        return this.cars;
    }
    
    public void setCars(Set<Car> cars) {
        this.cars = cars;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sale")
    public Set<Payment> getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set<Payment> payments) {
        this.payments = payments;
    }




}


